import gymnasium as gym
import coverage_gridworld  # noqa: F401
from stable_baselines3 import PPO
import time

# 1. Curriculum Maps (ordered easy → hard)
just_go_map = [
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]

safe_map = [
    [3, 0, 0, 2, 0, 2, 0, 0, 0, 0],
    [0, 2, 0, 0, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 2, 2, 2, 2, 2, 2, 0],
    [0, 2, 0, 0, 0, 2, 0, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
    [0, 2, 2, 2, 0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 2, 0, 2, 2, 0, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 0, 0]
]

maze_map = [
    [3, 2, 0, 0, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 2, 0, 2, 2],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 2, 0, 2, 2],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 4, 2, 4, 0, 0],
    [0, 0, 0, 2, 0, 0, 0, 0, 0, 0]
]

chokepoint_map = [
    [3, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0, 0, 4],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 4, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 4, 0, 4, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 2, 0, 0]
]

def main():
    # 1. Choose the map you want to test on
    # (Change this to safe_map, maze_map, etc. to test different phases)
    test_map = chokepoint_map 

    # 2. Initialize the environment in Human mode for rendering
    env = gym.make("standard", render_mode="human", predefined_map=test_map)

    # 3. Load the PPO model
    # Update this string if you named your final save file differently!
    model_path = "group9_ppo_agent_final" 
    print(f"Loading PPO model from {model_path}.zip...")
    
    try:
        model = PPO.load(model_path)
    except FileNotFoundError:
        print(f"Error: Could not find {model_path}.zip!")
        print("Please check the exact filename generated by train_agent.py.")
        return

    # 4. Reset environment and start test loop
    obs, info = env.reset()
    done = False
    trunc = False
    step_count = 0

    print("Starting visual evaluation...")
    
    while not (done or trunc):
        # deterministic=False allows PPO to use its stochastic nature
        # This prevents it from getting completely "paralyzed" by fear
        action, _states = model.predict(obs, deterministic=False)
        
        obs, reward, done, trunc, info = env.step(action)
        step_count += 1
        
        # Adjust sleep time to make the rendering faster/slower
        time.sleep(0.15) 

    # 5. Print Final Results
    print("\n--- Episode Finished ---")
    if info.get("game_over"):
        print("Status: GAME OVER (Caught by enemy or hit a trap)")
    elif info.get("cells_remaining") == 0:
        print("Status: SUCCESS (Cleared all unvisited cells!)")
    else:
        print("Status: TIMEOUT (Ran out of maximum steps)")

    coverage = info.get("total_covered_cells", "?")
    coverable = info.get("coverable_cells", "?")
    
    print(f"Total Steps Taken: {step_count}")
    print(f"Final Coverage: {coverage} / {coverable} cells")

    env.close()

if __name__ == "__main__":
    main()