import gymnasium as gym
import coverage_gridworld  # noqa: F401
from stable_baselines3 import PPO
import time

# DEFINED TRAINING MAPS
just_go_map = [
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]

safe_map = [
    [3, 0, 0, 2, 0, 2, 0, 0, 0, 0],
    [0, 2, 0, 0, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 2, 2, 2, 2, 2, 2, 0],
    [0, 2, 0, 0, 0, 2, 0, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
    [0, 2, 2, 2, 0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 2, 0, 2, 2, 0, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 0, 0]
]

maze_map = [
    [3, 2, 0, 0, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 2, 0, 2, 2],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 2, 0, 2, 2],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 4, 2, 4, 0, 0],
    [0, 0, 0, 2, 0, 0, 0, 0, 0, 0]
]

chokepoint_map = [
    [3, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0, 0, 4],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 4, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 4, 0, 4, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 2, 0, 0]
]

# evaluation maps unseen by agent
test_map1 = [
    [3, 0, 0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 2, 0, 2, 2, 2, 0],
    [0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
    [2, 2, 2, 2, 2, 0, 0, 0, 2, 0],
    [0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    [0, 2, 2, 2, 2, 2, 2, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]

test_map2 = [
    [3, 0, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 2, 2, 2, 2, 2, 0],
    [0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 0, 4, 0, 0, 0],
    [2, 2, 2, 0, 2, 2, 2, 2, 2, 2],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 2, 2, 2, 2, 2, 2, 0, 0],
    [0, 0, 0, 0, 4, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 2, 0, 0]
]

test_map3 = [
    [3, 2, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, 2, 2, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 0, 0, 0, 2, 0],
    [0, 0, 0, 2, 0, 4, 0, 0, 2, 0],
    [2, 2, 0, 2, 0, 0, 0, 0, 2, 0],
    [0, 0, 0, 2, 2, 2, 0, 2, 2, 0],
    [0, 4, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 2, 2, 2, 0, 2, 2, 0],
    [2, 2, 2, 2, 0, 0, 0, 4, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]

# map testing order
maps_to_test = [
    ("JustGo (Train)", just_go_map),
    ("Safe (Train)", safe_map),
    ("Maze (Train)", maze_map),
    ("Chokepoint (Train)", chokepoint_map),
    ("Test 1 (Easy)", test_map1),
    ("Test 2 (Medium)", test_map2),
    ("Test 3 (Hard)", test_map3)
]

def main():

    model_path = "group9_ppo_agent_final" 
    print(f"Loading PPO model from {model_path}.zip...")
    
    try:
        model = PPO.load(model_path)
    except FileNotFoundError:
        print(f"Error: Could not find {model_path}.zip!")
        print("Please check the exact filename generated by train_agent.py.")
        return

    num_runs = 20
    results = {}

    print(f"\nRunning {num_runs} automated tests per map...")
    print("(Visual rendering is disabled for speed. This should only take a few seconds.)\n")
    
    # loop to iterate through every map with our loaded model
    for map_name, map_layout in maps_to_test:
        env = gym.make("standard", render_mode=None, predefined_map=map_layout)
        
        run_percentages = []
        
        for run in range(num_runs):
            obs, info = env.reset()
            done = False
            trunc = False
            
            while not (done or trunc):
                action, _states = model.predict(obs, deterministic=False)
                obs, reward, done, trunc, info = env.step(action)
            
            # calculate percentage for episode
            coverage = info.get("total_covered_cells", 0)
            coverable = info.get("coverable_cells", 1)
            percentage = (coverage / coverable) * 100.0
            
            run_percentages.append(percentage)
            
        env.close()
        
        # calculate average for map
        avg_percentage = sum(run_percentages) / len(run_percentages)
        results[map_name] = avg_percentage
        print(f"✔ {map_name} complete.")

    # summary table
    print("\n" + "=" * 46)
    print(f"| {'Map Name':<20} | {'Average Coverage':<18} |")
    print("-" * 46)
    for map_name, avg_cov in results.items():
        print(f"| {map_name:<20} | {avg_cov:>16.2f} % |")
    print("=" * 46 + "\n")

if __name__ == "__main__":
    main()