import gymnasium as gym
import coverage_gridworld  # noqa: F401
from stable_baselines3 import PPO
import time

# 1. Curriculum Maps (ordered easy → hard)
just_go_map = [
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]

safe_map = [
    [3, 0, 0, 2, 0, 2, 0, 0, 0, 0],
    [0, 2, 0, 0, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 2, 2, 2, 2, 2, 2, 0],
    [0, 2, 0, 0, 0, 2, 0, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
    [0, 2, 2, 2, 0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 2, 0],
    [0, 2, 0, 2, 0, 2, 2, 0, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 0, 0]
]

maze_map = [
    [3, 2, 0, 0, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 2, 0, 2, 2],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 2, 0, 2, 2],
    [0, 2, 0, 2, 0, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 2, 2, 2, 0],
    [0, 2, 0, 2, 0, 4, 2, 4, 0, 0],
    [0, 0, 0, 2, 0, 0, 0, 0, 0, 0]
]

chokepoint_map = [
    [3, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0, 0, 4],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 4, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 4, 0, 4, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 2, 0, 0]
]

# Create an iterable list of all maps
maps_to_test = [
    ("JustGo", just_go_map),
    ("Safe", safe_map),
    ("Maze", maze_map),
    ("Chokepoint", chokepoint_map)
]

def main():
    # 1. Load the PPO model
    model_path = "group9_ppo_agent_final" 
    print(f"Loading PPO model from {model_path}.zip...")
    
    try:
        model = PPO.load(model_path)
    except FileNotFoundError:
        print(f"Error: Could not find {model_path}.zip!")
        print("Please check the exact filename generated by train_agent.py.")
        return

    num_runs = 20
    results = {}

    print(f"\nRunning {num_runs} automated tests per map...")
    print("(Visual rendering is disabled for speed. This should only take a few seconds.)\n")
    
    # 2. Iterate through every map
    for map_name, map_layout in maps_to_test:
        # Note: render_mode is None so we can brute-force the calculations instantly
        env = gym.make("standard", render_mode=None, predefined_map=map_layout)
        
        run_percentages = []
        
        # Run 20 episodes on the current map
        for run in range(num_runs):
            obs, info = env.reset()
            done = False
            trunc = False
            
            while not (done or trunc):
                # deterministic=False keeps the agent exploring and sneaking naturally
                action, _states = model.predict(obs, deterministic=False)
                obs, reward, done, trunc, info = env.step(action)
            
            # Calculate the percentage for this specific episode
            coverage = info.get("total_covered_cells", 0)
            coverable = info.get("coverable_cells", 1)  # Default to 1 to avoid ZeroDivisionError
            percentage = (coverage / coverable) * 100.0
            
            run_percentages.append(percentage)
            
        env.close()
        
        # 3. Calculate average for the map
        avg_percentage = sum(run_percentages) / len(run_percentages)
        results[map_name] = avg_percentage
        print(f"✔ {map_name} complete.")

    # 4. Print the final summary table
    print("\n" + "=" * 42)
    print(f"| {'Map Name':<15} | {'Average Coverage':<18} |")
    print("-" * 42)
    for map_name, avg_cov in results.items():
        print(f"| {map_name:<15} | {avg_cov:>16.2f} % |")
    print("=" * 42 + "\n")

if __name__ == "__main__":
    main()